nuxt-community/composition-api

src/index.ts

Somehow the `useContext` API seems not available even though it appears & is mentioned on README.
Please do not mind closing this PR if there's any particular reason not to make it available until the certain future point.

fix: make `useContext` API available

---

package.json
src/context.ts
src/fetch.ts
src/index.ts
src/ssr-ref.ts
test/fixture/nuxt.config.js

fix: allow custom `globalContext` and `globalNuxt`

---

src/async.ts

Fixes #210. This will convert all callback given to useAsync to Promises. Ensures that if the callback is any sort of promise it will resolve properly. If the function is not a promise, Promise.resolve() shouldn't cause any issues.

fix: use `Promise.resolve()` to cover all possible promise cases

---

src/entrypoint.ts

Fixes #238 
Looks like the only place in the codebase where `markReactive` was mentioned was in `entrypoint.ts` where it was just being exported from `@vue/composition-api`. All I have done here is to remove the export which seems to fix the issue for me.
I guess this could be a breaking change if someone was relying on importing `markReactive` from the package, but this is in line with `@vue/composition-api` so the change would need to be handled anyway.

fix: remove `markReactive` export

---

package.json
src/entrypoint.ts
src/fetch.ts
src/meta.ts
yarn.lock

chore: bump @vue/composition-api, fix #244

---

docs/content/en/useMeta.md
src/meta.ts
test/e2e/meta.ts
test/fixture/pages/meta.vue

**Usage**:
In addition to the existing usage for `useMeta`, this adds the possibility to pass a function which will effectively generate a computed head state and be merged with any other head values.
```
useMeta(() => ({ title: message.value }))
```
nuxt-community/typescript-template#225
closes #254

feat: allow computed properties within `useMeta`

---

src/meta.ts

Trying to fix https://github.com/nuxt-community/composition-api/issues/267
I removed the properties declared on the `$options` and declared them directly on the instance.

fix: prevent `useMeta` from sharing state in ssr

---

src/index.ts
templates/plugin.js

The current setting will create a plugin that imports `core-js` for both server-side and  client-side
```
// Necessary polyfill for Composition API support for IE11
import 'core-js/features/reflect/own-keys'
``` 
However, server-side is no need to use `core-js`
Therefore this PR separate plugin into server-side & client-side in order to get rid of `core-js` from the server-side

feat: separate plugin into server-side & client-side

---

src/index.ts

fix #303.
It could be good to add some tests to validate the behaviour, but I actually have no idea how to test that.
👋

feat: add compositionAPI flag in jsx babel configuration

---

src/fetch.ts
test/e2e/fetch.ts
test/fixture/pages/index.vue
test/fixture/pages/ttfb.vue

Fixes: #359 
Sets the default `useFetch` delay to `0` 😋

fix: set `useFetch` delay to 0 by default

---

src/index.ts
test/unit/ssr-ref.spec.ts

* means @nuxtjs/composition-api can truly be in `devDependencies`

fix: transpile `@vue/composition-api`

---

docs/content/en/getting-started/gotchas.md

Without these changes, the page says basically the same thing twice. Alternatively, we could remove the description and use the content.

Remove duplicate content in gotchas.md

---

src/runtime/templates/register.js

As a result of https://github.com/nuxt-community/composition-api/commit/9d4165a3511ffeb2cf1e0584a303565b41b0f968, this line is being added to middleware.js
> import $c289ad42 from './composition-api/register.js'
Which fails on vite since `register.js` is not exporting any default.
For a longer run, I HIGHLY recommend avoiding this workaround for ordering and adding register.js to build entry

fix(runtime): export default from register entry

---

docs/pages/en/1.getting-started/2.setup.md

According to https://github.com/nuxt-community/composition-api/issues/44#issuecomment-808558924 this only applies in rare circumstances.
Instead of simply deleting it, maybe we should add it to the `ssrRef` *or* Gotcha doc page? 🤔

docs: remover "2 second interval" rule for ssg

---

docs/pages/en/index.md

In the snippet tells to install with `--dev` flag, but is required in the builded app

docs: remove `--dev` flag in home page snippet

---

src/module/index.ts

This PR aliases vue to a single Vue instance, required when using other libraries that resolve vue differently. Normally this would have just added bytes to the bundle, but because of how the composition API is implemented, it breaks reactivity.
resolves https://github.com/nuxt-community/composition-api/issues/507, resolves https://github.com/nuxt-community/composition-api/issues/521

fix: resolve to single vue instance

---

README.md
docs/pages/en/1.getting-started/1.introduction.md
src/module/index.ts

This can be disabled with the following options in `nuxt.config`:
```js
export default {
capi: {
disableMigrationWarning: true
}
}
```

chore: add nuxt bridge migration recommendation

---

docs/pages/en/6.API/1.useAsync.md

When I first tried to work with this, I was at a loss as to why the code wasn't running as the Nuxt HTTP module wasn't properly configured to work in my project. So, I have explained where this comes from and how to add the module to prevent other people reading the docs from having the same issue.

docs: clarify where `$http` is coming from

---

docs/pages/en/2.packages/3.useMeta.md

Add this note so it makes more clear that `defineComponent` from `vue` or `@vue/composition-api` won't work with `useMeta`
Related: https://github.com/nuxt-community/composition-api/issues/651

docs(meta): add note about defineComponent import

---

src/runtime/composables/async.ts

Related to #493
If a falsy value is returned from useAsync, the client will always run the request again.
You could completely allow falsy values by adding a `hasRun` ssrRef but I fear it would pollute the global space.
So, as a compromise, with this change you can avoid having the client re-run a request if you return **any falsy value other than null (and void)**
Edit:
I guess another solution would be to convert the default ref value to an object, something like `{ data: null, hasRun: false }` and maintain the single ssrRef that's already generated currently. But I think the proposed change is simple enough and really has no downsides to current behavior afaik.

fix: allow returning of falsy values from useAsync

---

package.json

When this peer dependency was added there have actually existed an [explicit import](https://github.com/nuxt-community/composition-api/blob/d94c40eb8b581bd9f1ab888310985966c7126643/src/fetch.ts#L7-L7) that referenced it but it's not the case anymore so this should not be needed.

fix: remove `@nuxt/vue-app` peer dependency
